on: [push, workflow_dispatch]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
      - uses: nttld/setup-ndk@v1
        with:
          # NOTE: this must match NDK version in build.gradle `ext.ndkVersion`
          ndk-version: r25c
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew build
      - uses: actions/upload-artifact@v3
        with:
          name: libuvccamera
          path: libuvccamera/build/outputs/aar/*.aar
      - uses: actions/upload-artifact@v3
        with:
          name: usbCameraCommon
          path: usbCameraCommon/build/outputs/aar/*.aar

